"""
Mezzold TermArt - Project Architecture File Tree Module
Renders an elegant Unix terminal directory tree with developer file icons,
branch glyphs, and color-coded hierarchy cards in pure SVG.
Inspired by Unix tree and eza.
"""
import os
import html
from typing import Dict, Any, List
from ...core.plugin import BasePlugin
from ...core.registry import registry

DEFAULT_TREE = [
    ("📁 src/termart/", "#58a6ff", True),
    ("  ├── 📁 core/", "#79c0ff", True),
    ("  │   ├── 🐍 plugin.py", "#7ee787", False),
    ("  │   ├── 🐍 registry.py", "#7ee787", False),
    ("  │   └── 🐍 animator.py", "#7ee787", False),
    ("  ├── 📁 modules/", "#79c0ff", True),
    ("  │   ├── 📁 image/", "#d2a8ff", True),
    ("  │   │   ├── 🎨 drawille_engine.py", "#7ee787", False),
    ("  │   │   ├── 🎨 dither_engine.py", "#7ee787", False),
    ("  │   │   └── 🎨 glitch_art.py", "#7ee787", False),
    ("  │   ├── 📁 fx/", "#d2a8ff", True),
    ("  │   │   ├── 🌀 cmatrix_svg.py", "#7ee787", False),
    ("  │   │   └── 🌸 cbonsai_svg.py", "#7ee787", False),
    ("  │   └── 📁 profile/", "#d2a8ff", True),
    ("  │       ├── 📊 heatmap.py", "#7ee787", False),
    ("  │       └── 🎮 pokemon_card.py", "#7ee787", False),
    ("  └── 📁 ui/web/app.py", "#ffa657", False),
    ("📄 README.md", "#e3b341", False),
    ("⚙️ pyproject.toml", "#a5d6ff", False)
]

@registry.register
class FileTreePlugin(BasePlugin):
    name = "file_tree"
    category = "profile"
    description = "Unix directory tree architecture visualizer with file icons and branch glyphs in SVG"

    def run(
        self,
        tree_lines: List[str] = None,
        title: str = "mezzold-termart-suite",
        out_svg: str = "file_tree.svg",
        username: str = "architect",
        **kwargs
    ) -> Dict[str, Any]:
        canvas_w = 680
        titlebar_h = 34
        pad_x = 28

        entries = []
        if tree_lines:
            for l in tree_lines:
                entries.append((l, "#7ee787" if l.endswith((".py", ".rs", ".go")) else "#58a6ff", "/" in l))
        else:
            entries = DEFAULT_TREE

        line_h = 20.0
        canvas_h = int(titlebar_h + len(entries) * line_h + 50)
        font_size = 12.5
        start_y = titlebar_h + 30

        parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{canvas_w}" height="{canvas_h}" '
            f'viewBox="0 0 {canvas_w} {canvas_h}" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace">',
            f'<rect width="{canvas_w}" height="{canvas_h}" rx="12" fill="#0d1117"/>',
            f'<rect x="0.5" y="0.5" width="{canvas_w-1}" height="{canvas_h-1}" rx="12" fill="none" stroke="#30363d" stroke-width="1"/>',
            f'<line x1="0" y1="{titlebar_h}" x2="{canvas_w}" y2="{titlebar_h}" stroke="#30363d"/>'
        ]

        for i, c in enumerate(["#ff5f56", "#ffbd2e", "#27c93f"]):
            parts.append(f'<circle cx="{18 + i*16}" cy="{titlebar_h/2}" r="5" fill="{c}"/>')

        parts.append(
            f'<text x="{canvas_w/2}" y="{titlebar_h/2 + 4}" fill="#7d8590" font-size="12" '
            f'text-anchor="middle">{username}@repo: ~$ tree -L 3 --dirsfirst {title}/</text>'
        )

        for ry, (text, col, is_dir) in enumerate(entries):
            y_pos = start_y + ry * line_h
            weight = 'font-weight="bold"' if is_dir else ''
            safe_text = html.escape(text)
            parts.append(
                f'<text xml:space="preserve" x="{pad_x}" y="{y_pos:.1f}" font-size="{font_size:.1f}" fill="{col}" {weight}>{safe_text}</text>'
            )

        # Footer summary line
        parts.append(
            f'<text x="{pad_x}" y="{canvas_h - 14}" fill="#7d8590" font-size="11">'
            f'6 directories, 13 files • Generated by Mezzold TermArt Suite</text>'
        )

        parts.append('</svg>')
        svg_content = "".join(parts)

        if out_svg:
            os.makedirs(os.path.dirname(os.path.abspath(out_svg)), exist_ok=True)
            with open(out_svg, "w", encoding="utf-8") as f:
                f.write(svg_content)

        return {"status": "success", "output_path": out_svg, "entries": len(entries)}
